api_platform:
    title: CoHealth API
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 20
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        jsonld: ["application/ld+json"]
        multipart: ["multipart/form-data"]
