<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260610120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add mission observations and their authors.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE observation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mission_id INT NOT NULL, owner_id INT NOT NULL, uuid UUID NOT NULL, type VARCHAR(255) NOT NULL, observed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, value NUMERIC(8, 2) DEFAULT NULL, systolic SMALLINT DEFAULT NULL, diastolic SMALLINT DEFAULT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5773B4FD17F50A6 ON observation (uuid)');
        $this->addSql('CREATE INDEX IDX_C5773B4FBE6CAE90 ON observation (mission_id)');
        $this->addSql('CREATE INDEX IDX_C5773B4F7E3C61F9 ON observation (owner_id)');
        $this->addSql('CREATE INDEX observation_mission_observed_at_idx ON observation (mission_id, observed_at)');
        $this->addSql('ALTER TABLE observation ADD CONSTRAINT FK_C5773B4FBE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE observation ADD CONSTRAINT FK_C5773B4F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE observation');
    }
}
