<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260611130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add private documents attached to missions.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mission_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mission_id INT NOT NULL, uuid UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, file_path VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(255) DEFAULT NULL, file_size INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_547C7B88D17F50A6 ON mission_document (uuid)');
        $this->addSql('CREATE INDEX IDX_547C7B88BE6CAE90 ON mission_document (mission_id)');
        $this->addSql('ALTER TABLE mission_document ADD CONSTRAINT FK_547C7B88BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE mission_document');
    }
}
