<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260612130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add mandate groups and mandates.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mandate_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, uuid UUID NOT NULL, patient JSON NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C344A5C4D17F50A6 ON mandate_group (uuid)');
        $this->addSql('CREATE INDEX IDX_C344A5C47E3C61F9 ON mandate_group (owner_id)');
        $this->addSql('CREATE TABLE mandate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mandate_group_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, mission_id INT DEFAULT NULL, uuid UUID NOT NULL, category VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rejected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, begin_date DATE NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_197D0FEED17F50A6 ON mandate (uuid)');
        $this->addSql('CREATE INDEX IDX_197D0FEE5226364A ON mandate (mandate_group_id)');
        $this->addSql('CREATE INDEX IDX_197D0FEEF4BD7827 ON mandate (assigned_to_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_197D0FEEBE6CAE90 ON mandate (mission_id)');
        $this->addSql('ALTER TABLE mandate_group ADD CONSTRAINT FK_854A33087E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandate ADD CONSTRAINT FK_6C18C7F0366A62A7 FOREIGN KEY (mandate_group_id) REFERENCES mandate_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandate ADD CONSTRAINT FK_6C18C7F0E74CA17C FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mandate ADD CONSTRAINT FK_6C18C7F0BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE mandate');
        $this->addSql('DROP TABLE mandate_group');
    }
}
