coop_tilleuls_forgot_password:
    resource: .
    type: coop_tilleuls_forgot_password
    prefix: /forgot-password

coop_tilleuls_forgot_password.get_token:
    path: /forgot-password/{tokenValue}
    methods: [GET]
    controller: App\Controller\ValidatePasswordTokenController
