<?php

namespace App\Model;

enum PrincipalCategoryEnum: string
{
    case AUTRE = "AUTRE";
    case CHIRURGIE = "CHIRURGIE";
    case MEDICINE = "MEDICINE";
    case PEDIATRIE = "PEDIATRIE";
    case PSYCHIATRIE = "PSYCHIATRIE";
    case RADIOLOGIE = "RADIOLOGIE";
    case CABINETS_DE_GROUPE = "CABINETS_DE_GROUPE";
    case CARDIOLOGIE = "CARDIOLOGIE";
    case CAS_SPECIAUX = "CAS_SPECIAUX";
    case CHIRURGIEN_DENTISTE = "CHIRURGIEN_DENTISTE";
    case CHIRURGIE_PLASTIQUE_RECONSTRUCTIVE_ET_ESTHETIQUE = "CHIRURGIE_PLASTIQUE_RECONSTRUCTIVE_ET_ESTHETIQUE";
    case CHIRURGIE_ORTHOPEDIQUE_ET_TRAUMATOLOGIQUE = "CHIRURGIE_ORTHOPEDIQUE_ET_TRAUMATOLOGIQUE";
    case CLINIQUE_HOPITAL = "CLINIQUE_HOPITAL";
    case HOPITAL_UNIVERSITAIRE = "HOPITAL_UNIVERSITAIRE";
    case CLINIQUE_SPECIALISEE_CHIRURGIE = "CLINIQUE_SPECIALISEE_CHIRURGIE";
    case CLINIQUE_SPECIALISEES_DIVERSE = "CLINIQUE_SPECIALISEES_DIVERSE";
    case CLINIQUE_PSYCHIATRIQUE = "CLINIQUE_PSYCHIATRIQUE";
    case CLINIQUE_DE_READAPTATION = "CLINIQUE_DE_READAPTATION";
    case DERMATOLOGIE_ET_VENEREOLOGIE = "DERMATOLOGIE_ET_VENEREOLOGIE";
    case ENDOCRINOLOGIE_ET_DIABETOLOGIE = "ENDOCRINOLOGIE_ET_DIABETOLOGIE";
    case GYNECOLOGIE_ET_OBSTETRIQUE = "GYNECOLOGIE_ET_OBSTETRIQUE";
    case INSTITUTION_DE_SOINS_AMBULATOIRES_DISPENSES_PAR_DES_CHIRURGIENS_DENTISTES = "INSTITUTION_DE_SOINS_AMBULATOIRES_DISPENSES_PAR_DES_CHIRURGIENS_DENTISTES";
    case MAISON_DE_NAISSANCE = "MAISON_DE_NAISSANCE";
    case MEDECINE_INTERNE_GENERALE = "MEDECINE_INTERNE_GENERALE";
    case MEDECINE_GENERALE = "MEDECINE_GENERALE";
    case MEDECINE_PRATICIENNE = "MEDECINE_PRATICIENNE";
    case NEUROLOGIE = "NEUROLOGIE";
    case OPHTALMOLOGIE = "OPHTALMOLOGIE";
    case OTO_RHINO_LARYNGOLOGIE = "OTO_RHINO_LARYNGOLOGIE";
    case PSYCHIATRIE_ET_PSYCHOTHERAPIE = "PSYCHIATRIE_ET_PSYCHOTHERAPIE";
    case PSYCHIATRIE_ET_PSYCHOTHERAPIE_PEDIATRIQUE = "PSYCHIATRIE_ET_PSYCHOTHERAPIE_PEDIATRIQUE";
    case UROLOGIE = "UROLOGIE";
}
